// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Substituir com credenciais do projeto church-hub Firebase

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6er89097FMlr1FZ-9nnj5O6AAYh-dBuQ',
    appId: '1:50041359262:web:b107f4572e59ca5bd4248f',
    messagingSenderId: '50041359262',
    projectId: 'church-hub-prod',
    authDomain: 'church-hub-prod.firebaseapp.com',
    storageBucket: 'church-hub-prod.firebasestorage.app',
    measurementId: 'G-5KMH7PREGL',
  );

  // Execute: flutterfire configure --project=<firebase-project-id>

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO01v1yWX0QOf6uRSi5NcrwJ3_wOJqLwg',
    appId: '1:50041359262:android:986131c1d9718bbdd4248f',
    messagingSenderId: '50041359262',
    projectId: 'church-hub-prod',
    storageBucket: 'church-hub-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6sGP6NCzAKDtPSLMvrx7FqqPjErZt3s',
    appId: '1:50041359262:ios:c8b37f5d5a8f00c3d4248f',
    messagingSenderId: '50041359262',
    projectId: 'church-hub-prod',
    storageBucket: 'church-hub-prod.firebasestorage.app',
    iosClientId: '50041359262-stb82njjeudg4tuocr76iub9br3npqb0.apps.googleusercontent.com',
    iosBundleId: 'com.churchhub.churchHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN6sGP6NCzAKDtPSLMvrx7FqqPjErZt3s',
    appId: '1:50041359262:ios:97e9b00ca873a60ed4248f',
    messagingSenderId: '50041359262',
    projectId: 'church-hub-prod',
    storageBucket: 'church-hub-prod.firebasestorage.app',
    iosClientId: '50041359262-kafnnvhalvanpqkd59u21gi496fbtt9l.apps.googleusercontent.com',
    iosBundleId: 'com.church-hub.app',
  );

}